A blog is born
==============

:date: 2018-04-14 14:14
:modified: 2018-04-14 14:14
:tags: internet, asciidoc, markdown, happy-end
:slug: introduction

So I tried to create a blog to rant about stuff. And first thing to rant about
is how to actually create blog. The current hype is to use static page
generators. There is like a ton of them. Most of them support Markdown, which
sucks because I prefer http://asciidoc.org/[Asciidoc]. It was here first,
some claim that it is more feature complete, doesn't have tons of dialects and
syntax is more straight forward (ok the last one is subjective).

There is still quite some that claim to support Asciidoc. Most of them claim to
support just Asciidoctor although I have no idea why they choose just one
specific implementation. But more importantly, most of it doesn't work well
anyway. So in the end I ended up using https://blog.getpelican.com/[Pelican]
which finally works (after trying several generators that claimed to have
Asciidoc and that didn't worked). Pelican supports Asciidoc only through
plugin, but hey, it works and it was using this or write something on my own.
Writing it myself wouldn't be that hard, but there is too much stuff already
and it is much better and harder to reuse then to start from scratch again
(more about it in another post).

Common errors I encountered in other generators included claiming Asciidoc
support and not actually having it. Maybe the worse option was actually having
some partial support where I ended up with HTML document included in another
HTML. Including full head and full css generated by Asciidoc. So that quite
sucked, but luckily I encountered Pelican and it seems to work correctly.

So my first post actually has some happy ending. Well, I promise the next time
I will swear more and complain more about how stuff sucks to actually fulfill
the mission of this blog.
