Twitter banned me before #FirstTweet!
=====================================

:date: 2018-04-15 12:12
:modified: 2018-04-15 18:18
:tags: internet, twitter, happy-end

I wrote my first link:introduction.html[blog post],
figured out how I want to manage the blog and got ready to get some visitors.
Given the content I currently have, presumably not many. I want to spread my
optimism online everywhere I could so I decided to create a twitter account for
my new identity.

I setup a name, selected a username, set my profile and got ready to tweet my
first tweet. And as I started to prepare it, my newly created account was
blocked because they claim that I look like a spambot.

Yeah, I took some effort to customise my background, to enter some bio, didn't
follow anybody and wanted to tweet something. Right, typical bot behaviour.

I can unblock my account if I enter my cell phone number. Yeah, that is exactly
what I had in mind when I setup separate identity for my ranting self - to give
everybody my personal cell number. Especially when even the real self account
doesn't have it entered anywhere.

I tried resetting password to prove I'm not a bot and that I'm reading e-mails,
but that was not enough, so I guess screw you twitter, no twitter for me and
I'll find some other media.

EDIT1: On the other hand I gave them a second chance and wrote an angry letter
to the support.

EDIT2: I got automatic answer that I should enter my cell number even though I
wrote in the request that I'm not willing to do so.

EDIT3: As I replied to the automatic mail, I got attention of a real person,
received apology and got my account unlocked, so everything ended well in the
end. But it looks like like that if you want to have some privacy online, it is
hard to use popular online tools.
